name: Sort files alphabetically

on:
  push:
    branches:
      - master

permissions:
  contents: write  

jobs:
  sort-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sort files alphabetically
        run: |
          ls | sort | while read file; do
            mv "$file" "temp_$file"
          done

          ls temp_* | sort | while read file; do
            mv "$file" "${file#temp_}"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Sort files alphabetically"
          git push
